apiVersion: v1
kind: Service
metadata:
  name: hris-service
spec:
  ports:
    # the port that this service should serve on
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: hris-app
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hris-deploy
  #namespace: jig-admin
  labels:
    app: hris-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hris-app
  template:
    metadata:
      labels:
        app: hris-app
    spec:
      serviceAccountName: cloud-proxy
      # dnsPolicy: Default
      # nodeSelector:
      #   beta.kubernetes.io/os: linux
      containers:
        - name: hris-app
          image: gcr.io/iagilityphp/hris:latest
          ports:
            - containerPort: 80
          imagePullPolicy: Always
          resources:

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: hris-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: admin.jobsingta.com
    http:
      paths:
      - backend:
          serviceName: hris-service
          servicePort: 80
        path: /
